batch_size: 256
experiment_name: ExpPose_single_encoder_vox_recon_decay
root: D:/rafdb_dataset/Image/aligned/aligned
train: D:/rafdb_dataset/EmoLabel/train_list.txt
val: D:/rafdb_dataset/EmoLabel/test_list.txt
test: D:/rafdb_dataset/EmoLabel/test_list.txt
gpu_ids: '3'
dataset: 'RAFDB' # BU3D or RAFDB or VOX
start_epochs: 0
neg_alpha: 1.6
pose_alpha: 0.001
#pose_alpha: 1.
wd: 1.0e-3
T: 0.07
num_threads: 3
save_epoch: 50
dim: 512
linear_dim: 6272
checkpoint_dir: ./checkpoints
epochs: 6000
continue_train: False
eval: False
eval_mode: 'exp' # 'exp' or 'pose' or 'face_cycle'
eval_epochs: 300
seed: 1234
log_path: ./logs
model_name: exppose # 小写
dataset_name: expposedb # 小写   expposedb
img_size: 64  # train 64 eval 100
lr: 1.0e-4
print_img: 50
print_loss : 20
load_model: ~ # None
save_img_dir: ./save_img
save_img: False
print_network: False
classes_num: 7
linear_lr: 1.0e-2
t_sne: False
op_path: /data/yuanyuan/wwb/self_sup/pre_process/new